version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=blast_app_db
      - JWT_SECRET=${JWT_SECRET}
      - GENBANK_API_KEY=${GENBANK_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mariadb:latest
    environment:
      - MARIA_DATABASE=blast_app_db
      - MARIA_USER=root
      - MARIA_PASSWORD=password
      - MARIA_ROOT_PASSWORD=password
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mariadb_data: