services:
  server:
    build:
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ${USERPROFILE}\.aws:/root/.aws:ro

  worker:
    build:
      dockerfile: worker/Dockerfile
    restart: unless-stopped
    volumes:
      - ${USERPROFILE}\.aws:/root/.aws:ro