services:
  # The API Server Service
  server:
    build:
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

  # The Background Worker Service
  worker:
    build:
      dockerfile: worker/Dockerfile
    restart: unless-stopped